### ISSUE TITLE
Term Change Request: Data Use Requirements

### ISSUE THREAD

**Issue by MKonopko** [EBISPOT/DUO#76]
Term definition change request: "data use requirements"

Per H3Africa Feedback:
> Original: Requirements indicate additional conditions set for use.
> 
> Changed: Requirements indicate additional conditions _needed_ for use.
> 
> Rationale: Small change, due to separation of requirements and restrictions.

@mamanambiya would you be able to provide a use case that shows how the original does not work for you?  Thanks!

**Comment by mamanambiya** [comment]
The original isn't faulty. We added this distinction between restrictions and requirements to make the difference clear within the structure of the ontology. And it would be easier to identify applicable codes from consent form, because the language used for restrictions vs requirement is different.

**Comment by mcourtot** [comment]
I'm not sure I see the difference, let's chat further

**Comment by mcourtot** [comment]
Lyndon and @mamanambiya indicate no further change required
