### ISSUE TITLE
Update DUO term categories, titles, and hierarchy display

### ISSUE THREAD

**Issue by solideoglori** [EBISPOT/DUO#94]
![image](https://user-images.githubusercontent.com/52168754/98697762-44dc4780-2343-11eb-8d86-6a38f1bebf23.png)

Update categories and hierarchy to reflect:

1. the initial definition of a permitted scope of research by choosing one of the data use permissions
2. the adaptation of the permitted scope by the application of data use modifier terms which further limit, prohibit, or add requirements to research done in the permitted scope

**Comment by mcourtot** [comment]
A couple of comments:
- instead of DUO_0000005 GRU_CC, use DUO_0000042 GRU. GRU_CC should be depreacted as per #45 This reflects the current hierarchy as well
![Screenshot 2020-11-10 at 07 55 25](https://user-images.githubusercontent.com/2214135/98645624-29b10e00-232a-11eb-8b9d-500538d39ce3.png)

- I wasn't sure whether the grey italic sentences were meant as definitions or just explanatory notes; if the former I'd like to reword them slightly to omit the mention of cardinality of use, which doesn't define the meaning of the term. We could include it as an example of usage or editor note for example.

**Comment by solideoglori** [comment]
Updated GRU_CC to GRU

As for the grey text, agree to add as an editor note.

**Comment by solideoglori** [comment]
Updates:

- Data Use Limitation -> Data Use Permission
- GSO, NMDS, RS moved to secondary hierarchy
- Deprecate Research Use Only 
- Data Use Requirements -> Data Use Modifier (definitions of terms updated to reference 'modifiers' instead of 'requirements')
